version: '3.8'
name: zhm-grafana
services:
  grafana:
    image: grafana/grafana:latest
    container_name: zhm-grafana
    ports:
      - "3000:3000"
    volumes:
      - D:\docker_data\grafana\etc:/etc/grafana
      - D:\docker_data\grafana\lib:/var/lib/grafana
    restart: always
    networks:
      - grafana_network

networks:
  grafana_network:
    driver: bridge
