version: '3.8'
name: zhm-home-assistant
services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    volumes:
      - D:\docker_data\home_assistant/config:/config
    ports:
      # 暴露 Web UI 端口和代理端口（用于分布式构建）
      - "8123:8123"
