version: '3.8'
name: zhm-mysql
services:
  mysql:
    image: mysql:8.0.39
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - D:\docker_data\mysql\conf\my.cnf:/etc/mysql/my.cnf
      - D:\docker_data\mysql\logs:/logs
      - D:\docker_data\mysql\data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
#    restart: always
