version: '3.8'
name: zhm-nexus3
services:
  nexus3:
    image: sonatype/nexus3:3.78.2
    #    restart: always
    container_name: zhm-nexus3-1
    ports:
      - "8081:8081"                 # 默认端口映射，可自定义外部端口（如18081）[3](@ref)
    volumes:
      - D:\docker_data\nexus\nexus-data:/nexus-data    # 数据持久化目录[1,3](@ref)

