version: '3.8'
name: zhm-nginx
services:
  nginx:
    image: nginx:latest
    container_name: zhm-nginx-1
    ports:
      - "11434:80"
    volumes:
      - /mnt/d/docker_data/nginx/conf/:/etc/nginx/                   # 配置文件
      - /mnt/d/docker_data/nginx/cert/:/etc/cert/                    # ssl证书
      - /mnt/d/docker_data/nginx/www/:/usr/share/nginx/html/         # 默认显示的index网页
      - /mnt/d/docker_data/nginx/logs/:/var/log/nginx/               # 日志文件

#    restart: always
