version: '3.8'
name: zhm-rockmq
services:
  zhm-rockmq-namesrv:
    image: apache/rocketmq:5.1.4
    container_name: rocketmq-namesrv
    command: sh mqnamesrv
    ports:
      - "9876:9876"
    environment:
      - JAVA_OPT_EXT=-server -Xms512m -Xmx512m -Xmn256m
    volumes:
      - D:\docker_data\rockmq\namesrv\logs:/home/rocketmq/logs
    networks:
      - rocketmq-net

  zhm-rockmq-broker:
    image: apache/rocketmq:5.1.4
    container_name: rocketmq-broker
    command: sh mqbroker -c /home/rocketmq/rocketmq-5.1.4/conf/broker.conf
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    environment:
      - JAVA_OPT_EXT=-server -Xms1g -Xmx1g -Xmn512m
    volumes:
      - D:\docker_data\rockmq\broker\logs:/home/rocketmq/logs
      - D:\docker_data\rockmq\broker\store:/home/rocketmq/store
      - D:\docker_data\rockmq\broker\conf\broker.conf:/home/rocketmq/rocketmq-5.1.4/conf/broker.conf
    depends_on:
      - zhm-rockmq-namesrv
    networks:
      - rocketmq-net

  zhm-rockmq-dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rocketmq-console
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rocketmq-namesrv:9876
    depends_on:
      - zhm-rockmq-namesrv
      - zhm-rockmq-broker
    networks:
      - rocketmq-net

networks:
  rocketmq-net:
    driver: bridge
    attachable: true